### ISSUE TITLE
KGI stuck after some time

### ISSUE THREAD

**Issue by svarogg** [kaspa-live/kaspa-graph-inspector#16]
After leaving kaspa.live open for some time, I've noticed that no more blocks are being added.

In the console there was a single error message:
```
Uncaught (in promise) TypeError: e.mergeSetRedIds is null
    M Block.ts:19
    V BlocksAndEdgesAndHeightGroups.ts:24
    setBlocksAndEdgesAndHeightGroups TimelineContainer.ts:65
    e Dag.ts:247
    c runtime.js:63
    _invoke runtime.js:293
    E runtime.js:118
```

Clicking a block immediately revealed the rest of the DAG, and the >> button.
Clicking the >> button resumed operation to normal.

**Comment by tiram88** [comment]
Could not reproduce the issue, which is quite old now.
Closing it for the moment.
