### ISSUE TITLE
Align the free space to the right of the tip of the DAG

### ISSUE THREAD

**Issue by Aleoami** [kaspa-live/kaspa-graph-inspector#32]
There's too much free space to the right of the tip of the DAG in some modes of the browser window: this is what it looks like on a FullHD monitor when the Firefox browser is in the fullscreen mode
![image](https://user-images.githubusercontent.com/14896367/166674645-99c15704-bb7b-473e-a4e1-37ae4ece93c9.png)
and this is how it looks when the browser is not maximized:
![image](https://user-images.githubusercontent.com/14896367/166675053-624b005a-1f1b-43b1-87c7-9dca9f372e46.png)
Too much free space to the right in the first case.

**Comment by tiram88** [comment]
Solved by #34
