### ISSUE TITLE
Add a switch to turn on a "compressed" visualization of blocks for the case of too many parallel ones

### ISSUE THREAD

**Issue by Aleoami** [kaspa-live/kaspa-graph-inspector#52]
There are times when we have much more blocks in parallel than it is possible to fit onto screen vertically. Can you maybe add a switch there that will turn on "compressed" visualization of such blocks? So they would be either overlaying partially, or maybe have the not a square view, but a rectangular one. So that all of these many vertical blocks fit onto screen at once.

**Comment by tiram88** [comment]
Although the feature developed does not work as you described it, it does covers pretty well the requirement of visually separating a large group of blocks grouped at the same DAA score.
