### ISSUE TITLE
Investigate mempool limits

### ISSUE THREAD

**Issue by svarogg** [kaspa-live/kaspa-graph-inspector#6]
Mempool should be limited to 1mil transactions, which translates to about 300 megabytes.
However, we saw a node in which (seemingly) mempool transactions took up to 2.3 gigs.

Write a stability-test that:
1. Fills the mempool up to the limit
2. Keeps adding more transactions, making sure eviction works
3. Starts mining blocks to make sure this cleans the mempool eventually.

**Comment by stasatdaglabs** [comment]
This appears to be a https://github.com/kaspanet/kaspad ticket. Closing.
