### ISSUE TITLE
Requesting specific hashes results in a blank page

### ISSUE THREAD

**Issue by elichai** [kaspa-live/kaspa-graph-inspector#7]
Example: http://kgi-testnet-3.daglabs-dev.com/?hash=ecc8bd82b1fbc5e63f270d081a790a7a5b1adbecaf9d458ef6c3689820682186

Proof that this is a real block: http://testnet-3.katnip.sh/#/block/ecc8bd82b1fbc5e63f270d081a790a7a5b1adbecaf9d458ef6c3689820682186

**Comment by tiram88** [comment]
This issue is quite old now and we have no way to verify the example anymore.

It might be related to a restart of KGI which, a that time, was clearing its database and, as larger history, was then processing the blocks available from its node from pruning point up to virtual.
